### ISSUE TITLE
Failing CVE Resource Dependencies

### ISSUE THREAD

**Issue by ghost** [Plecost/plecost#14]
`plecost_lib.libs.updaters.cves.update_cve` fails, because [nvd.nist.gov](url) hasn't been reachable for more than a week now. Maybe provide a mirror, or set `nvd_base_url` in `plecost_lib.libs.updaters.cves.update_cve` as list with multiple nvd sources, such as [nvd.nist.gov](url) and [cve.mitre.org](url) trying to obtain database/xml until success.

**Comment by cr0hn** [comment]
Fixed in release 1.1.1. Just update:

```bash
> pip install -U plecost
```
