### ISSUE TITLE
Feature Request: Specify host header

### ISSUE THREAD

**Issue by zachsis** [Plecost/plecost#20]
First of all, Thank you all for your work on this project! good stuff. 

I would like to suggest a feature request to add a flag/option to specify a separate host header. i.e.   i want to run plecost against `https://1.2.3.4/`    and specify the host header `Host: theactualdomain.com`. Would this be a realistic request?

**Comment by cr0hn** [comment]
Added in release 1.1.2. Just update: 

```bash
> pip3 install -U plecost
```
