### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Pablohn26** [Plecost/plecost#8]
Al ejecutar el script de instalación con python2 hay problemas de sintaxis pero el programa se instala. 
Una vez instalado, al ejecutarse con python2 da un fallo de sintaxis.

Sería bueno poner una advertencia y finalizar el script en el caso en el que se ejecute con python2 en vez de con python3. 
///////English////////

When you run the installation script with python2 there are syntax errors but the program is installed. Once it is installed, you get a syntax error when you run it with python2. 

Would be great to set a warning and finish the program when it is being launched with python2 instead of python3.

**Comment by cr0hn** [comment]
@Pablohn26 Gracias por la sugerencia. Añadido y comiteado en la rama develop.
